// Copyright 2023 Xiao Feng. All Rights Reserved.

#pragma once
#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GROUP_PLAYERS)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GROUP_BOT)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_PLAYERS_SUBORDINATE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ENEMY_SUBORDINATE)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_ENEMY_BOSS)